<a href="https://colab.research.google.com/github/Qualot/deep-learning-from-scratch-2/blob/colab/ch01/chap01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [ ]:
x.shape

(3,)

In [ ]:
x.ndim

1

In [ ]:
W = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
W.shape

(2, 3)

In [ ]:
W.ndim

2

In [ ]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
print(W+X)
print(W* X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [ ]:
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.dot(x, W1) + b1
print(h)

[[-1.67517324 -1.2606311   0.4321473   0.44368759]
 [-0.02687786  0.06616517 -1.42056922  0.55896597]
 [-1.31690317 -0.94554592 -0.09483314  0.44383855]
 [ 0.86858585  0.41160103 -0.67960431  0.97179479]
 [ 0.30574977 -0.02245881 -0.13539628  0.91470935]
 [ 0.66084486  0.51764602 -1.71825918  0.70232048]
 [-2.47597737 -2.3248803   3.28586019  0.77918801]
 [-0.89291228 -0.40244581 -1.51090344  0.28521323]
 [-0.89253765 -0.54627438 -0.84034306  0.4197065 ]
 [-0.26641457  0.20671675 -2.70327647  0.23119674]]


#Sigmoid

In [3]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [4]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) + b2
print(s)

[[ 0.23750363 -0.70731592  0.60243736]
 [ 1.37970831 -1.75914736 -0.2597799 ]
 [-0.53113983  0.29490959  1.00602221]
 [ 1.7713082  -2.65457606 -0.29710521]
 [ 0.41303389 -0.73544388  0.41298218]
 [ 0.23511675 -0.61454555  0.56066137]
 [ 1.12598279 -2.01264127  0.17778102]
 [ 0.07276304 -0.54933856  0.71076347]
 [ 0.91748472 -1.77051022  0.3031804 ]
 [ 1.71319684 -2.63247065 -0.21583336]]
